name: mobile_app

packages:
  - car_service_app
  - employee_app
  - core

scripts:
  analyze:
    exec: dart analyze .
  add:
    exec: flutter pub add $1
  gen:
    exec: dart pub run build_runner build -d


command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
    dependencies:

    dev_dependencies:
      build_runner: ^2.4.8
      flutter_lints: ^3.0.1