name: car_service_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  cupertino_icons: ^1.0.2
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  get_it: ^7.6.7
  provider: ^6.1.1
  auto_route: ^7.8.4
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  injectable: ^2.3.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  logger: ^2.0.2+1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1


flutter:
  generate: true

  uses-material-design: true

  assets:
     - assets/
     - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
